### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by apisit** [O3Labs/neo-ws-pub-sub#1]
- [x] Readme
- [x] Move config to config.json
- [x] Select Best node
- [x] Auto re-connect when get disconnected
- [ ] Compile and release.
- [x] Sample privatenet, testnet and mainnet
